class Button {
  constructor(engPrim, engAlt, rusPrim, rusAlt, keyCode, width) {
    this.text = {
      en: [engPrim, engAlt],
      ru: [rusPrim, rusAlt],
    };
    this.keyCode = keyCode;
    this.width = width;
  }
}

const keyMap = {
  Backquote: {
    keyCode: 192,
    key: '`',
    type: 'print',
    width: '100',
  },
  Digit1: {
    keyCode: 49,
    key: '1',
    type: 'print',
    width: '100',
  },
  Digit2: {
    keyCode: 50,
    key: '2',
    type: 'print',
    width: '100',
  },
  Digit3: {
    keyCode: 51,
    key: '3',
    type: 'print',
    width: '100',
  },
  Digit4: {
    keyCode: 52,
    key: '4',
    type: 'print',
    width: '100',
  },
  Digit5: {
    keyCode: 53,
    key: '5',
    type: 'print',
    width: '100',
  },
  Digit6: {
    keyCode: 54,
    key: '6',
    type: 'print',
    width: '100',
  },
  Digit7: {
    keyCode: 55,
    key: '7',
    type: 'print',
    width: '100',
  },
  Digit8: {
    keyCode: 56,
    key: '8',
    type: 'print',
    width: '100',
  },
  Digit9: {
    keyCode: 57,
    key: '9',
    type: 'print',
    width: '100',
  },
  Digit0: {
    keyCode: 48,
    key: '0',
    type: 'print',
    width: '100',
  },
  Minus: {
    keyCode: 173,
    key: '-',
    type: 'print',
    width: '100',
  },
  Equal: {
    keyCode: 61,
    key: '=',
    type: 'print',
    width: '100',
  },
  Backspace: {
    keyCode: 8,
    key: 'Backspace',
    type: 'func',
    width: '200',
  },
  Tab: {
    keyCode: 9,
    key: 'Tab',
    type: 'func',
    width: '150',
  },
  KeyQ: {
    keyCode: 81,
    key: 'q',
    type: 'print',
    width: '100',
  },
  KeyW: {
    keyCode: 87,
    key: 'w',
    type: 'print',
    width: '100',
  },
  KeyE: {
    keyCode: 69,
    key: 'e',
    type: 'print',
    width: '100',
  },
  KeyR: {
    keyCode: 82,
    key: 'r',
    type: 'print',
    width: '100',
  },
  KeyT: {
    keyCode: 84,
    key: 't',
    type: 'print',
    width: '100',
  },
  KeyY: {
    keyCode: 89,
    key: 'y',
    type: 'print',
    width: '100',
  },
  KeyU: {
    keyCode: 85,
    key: 'u',
    type: 'print',
    width: '100',
  },
  KeyI: {
    keyCode: 73,
    key: 'i',
    type: 'print',
    width: '100',
  },
  KeyO: {
    keyCode: 79,
    key: 'o',
    type: 'print',
    width: '100',
  },
  KeyP: {
    keyCode: 80,
    key: 'p',
    type: 'print',
    width: '100',
  },
  BracketLeft: {
    keyCode: 219,
    key: '[',
    type: 'print',
    width: '100',
  },
  BracketRight: {
    keyCode: 221,
    key: ']',
    type: 'print',
    width: '100',
  },
  Backslash: {
    keyCode: 220,
    key: '\\',
    type: 'print',
    width: '125',
  },
  CapsLock: {
    keyCode: 20,
    key: 'CapsLock',
    type: 'func',
    width: '150',
  },
  KeyA: {
    keyCode: 65,
    key: 'a',
    type: 'print',
    width: '100',
  },
  KeyS: {
    keyCode: 83,
    key: 's',
    type: 'print',
    width: '100',
  },
  KeyD: {
    keyCode: 68,
    key: 'd',
    type: 'print',
    width: '100',
  },
  KeyF: {
    keyCode: 70,
    key: 'f',
    type: 'print',
    width: '100',
  },
  KeyG: {
    keyCode: 71,
    key: 'g',
    type: 'print',
    width: '100',
  },
  KeyH: {
    keyCode: 72,
    key: 'h',
    type: 'print',
    width: '100',
  },
  KeyJ: {
    keyCode: 74,
    key: 'j',
    type: 'print',
    width: '100',
  },
  KeyK: {
    keyCode: 75,
    key: 'k',
    type: 'print',
    width: '100',
  },
  KeyL: {
    keyCode: 76,
    key: 'l',
    type: 'print',
    width: '100',
  },
  Semicolon: {
    keyCode: 59,
    key: ';',
    type: 'print',
    width: '100',
  },
  Quote: {
    keyCode: 222,
    key: "'",
    type: 'print',
    width: '100',
  },
  Enter: {
    keyCode: 13,
    key: 'Enter',
    type: 'func',
    width: '150',
  },
  ShiftLeft: {
    keyCode: 16,
    key: 'Shift',
    type: 'func',
    width: '175',
  },
  KeyZ: {
    keyCode: 90,
    key: 'z',
    type: 'print',
    width: '100',
  },
  KeyX: {
    keyCode: 88,
    key: 'x',
    type: 'print',
    width: '100',
  },
  KeyC: {
    keyCode: 67,
    key: 'c',
    type: 'print',
    width: '100',
  },
  KeyV: {
    keyCode: 86,
    key: 'v',
    type: 'print',
    width: '100',
  },
  KeyB: {
    keyCode: 66,
    key: 'b',
    type: 'print',
    width: '100',
  },
  KeyN: {
    keyCode: 78,
    key: 'n',
    type: 'print',
    width: '100',
  },
  KeyM: {
    keyCode: 77,
    key: 'm',
    type: 'print',
    width: '100',
  },
  Comma: {
    keyCode: 188,
    key: ',',
    type: 'print',
    width: '100',
  },
  Period: {
    keyCode: 190,
    key: '.',
    type: 'print',
    width: '100',
  },
  Slash: {
    keyCode: 191,
    key: '/',
    type: 'print',
    width: '100',
  },
  ShiftRight: {
    keyCode: 16,
    key: 'Shift',
    type: 'func',
    width: '100',
  },
  ArrowUp: {
    keyCode: 38,
    key: '△',
    type: 'print',
    width: '100',
  },
  Delete: {
    keyCode: 46,
    key: 'Delete',
    type: 'func',
    width: '100',
  },
  ControlLeft: {
    keyCode: 17,
    key: 'Control',
    type: 'func',
    width: '100',
  },
  OSLeft: {
    keyCode: 91,
    key: 'OS',
    type: 'func',
    width: '100',
  },
  AltLeft: {
    keyCode: 18,
    key: 'Alt',
    type: 'func',
    width: '100',
  },
  Space: {
    keyCode: 32,
    key: ' ',
    type: 'print',
    width: '700',
  },
  AltRight: {
    keyCode: 18,
    key: 'Alt',
    type: 'func',
    width: '100',
  },
  ControlRight: {
    keyCode: 17,
    key: 'Control',
    type: 'func',
    width: '175',
  },
  ArrowLeft: {
    keyCode: 37,
    key: '◁',
    type: 'print',
    width: '100',
  },
  ArrowDown: {
    keyCode: 40,
    key: '▽',
    type: 'print',
    width: '100',
  },
  ArrowRight: {
    keyCode: 39,
    key: '▷',
    type: 'print',
    width: '100',
  },
};

export default keyMap;
